### ISSUE TITLE
[BUG]Ticking mode is bugged

### ISSUE THREAD

**Issue by lyagush0n0k** [MrTransistorsChannel/AFK#2]
Bot can die in ticking mode using arrows.
Bot can die from TNT.
Bot can just from a punching by player

The way you can reproduce it:
1) Spawn it
2) Enable ticking
3) Kill it 
4) It's so simple
:)

**Comment by MrTransistorsChannel** [comment]
Most definitely caused by *3rd party plugins* that alter the damaging system of the game (i. e. OldCombatMechanics).
After some tests found out that sometimes the first damage event after disabling ticking actually goes through and if it`s enough to kill a player the bot dies, otherwise the damage doesn't apply. This is a very minor issue which is probably caused by the way Minecraft handles damage
